[project]
name = "temp-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.14.0",
    "mysql-connector-python>=9.5.0",
    "platformdirs>=4.5.1",
    "sql-connectors>=1.0.2",
]
